version: "3.8"
services:
  redis:
    container_name: "redis"
    image: "docker.io/library/redis:7.2.4"
    volumes:
    - "redis-data:/data"
    ports:
    - target: 6379
      published: 6379
    command:
    - "--save"
    - "2"
    - "1"
    restart: unless-stopped
  mongodb:
    container_name: "mongodb"
    image: "docker.io/library/mongo:7.0.5"
    environment:
      MONGO_INITDB_DATABASE: "projections"
    volumes:
    - "mongodb-data:/data/db"
    ports:
    - target: 27017
      published: 27017
    restart: unless-stopped
  rabbitmq:
    container_name: "rabbitmq"
    image: "docker.io/library/rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "kuskwnyIzGmNzjEYkkbXe7"
    ports:
    - target: 5672
      published: 5672
    - target: 15672
      published: 15672
    command:
    - "/bin/bash"
    - "-c"
    - "rabbitmq-plugins enable --offline rabbitmq_mqtt; rabbitmq-server"
    restart: unless-stopped
  webapp:
    container_name: "webapp"
    image: "webapp:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      Orleans__Clustering__ProviderType: "Redis"
      Orleans__Clustering__ServiceKey: "redis"
      ConnectionStrings__redis: "redis:6379"
      Orleans__ClusterId: "a1d!dP4yLl9YfIsRVgIfcrB9!"
      Orleans__ServiceId: "yeu1nn93vQ2chrz0io6sMBaMJ"
      Orleans__EnableDistributedTracing: "true"
      Orleans__GrainStorage__games__ProviderType: "Redis"
      Orleans__GrainStorage__games__ServiceKey: "redis"
      Orleans__Endpoints__SiloPort: "8000"
      Orleans__Endpoints__GatewayPort: "8001"
      ConnectionStrings__projections: "mongodb://mongodb:27017/projections"
      ConnectionStrings__rabbitmq: "amqp://guest:kuskwnyIzGmNzjEYkkbXe7@rabbitmq:5672"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    - target: 8000
      published: 10002
    - target: 8001
      published: 10003
    restart: unless-stopped
volumes:
  redis-data: {}
  mongodb-data: {}
