version: "3.8"
services:
  redis:
    container_name: "redis"
    image: "redis:latest"
    ports:
    - target: 6379
      published: 6379
    restart: unless-stopped
  redis-replica1:
    container_name: "redis-replica1"
    image: "redis:latest"
    command:
    - "redis-server"
    - "--slaveof"
    - "redis"
    - "6379"
    - "--port"
    - "6380"
    restart: unless-stopped
  apiservice:
    container_name: "apiservice"
    image: "apiservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      Orleans__Clustering__ProviderType: "RedisContainer"
      Orleans__Clustering__ServiceKey: "redis"
      ConnectionStrings__redis: "redis:6379"
      Orleans__GrainStorage__WeatherForecasts__ProviderType: "RedisContainer"
      Orleans__GrainStorage__WeatherForecasts__ServiceKey: "redis"
      Orleans__ClusterId: "e4c5c3191de74b9b88710af0f0ee20c7"
      Orleans__EnableDistributedTracing: "true"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
  webfrontend:
    container_name: "webfrontend"
    image: "webfrontend:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      services__apiservice__0: "http://apiservice:8080"
      services__apiservice__1: "https://apiservice:8443"
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003
    restart: unless-stopped
