version: "3.8"
services:
  redis:
    container_name: "redis"
    image: "docker.io/library/redis:7.2.4"
    volumes:
    - "redis-data:/data"
    ports:
    - target: 6379
      published: 6381
    command:
    - "--save"
    - "2"
    - "1"
    restart: unless-stopped
  redis-replica1:
    container_name: "redis-replica1"
    image: "redis:latest"
    command:
    - "redis-server"
    - "--slaveof"
    - "redis"
    - "6379"
    - "--port"
    - "6380"
    restart: unless-stopped
  webapp:
    container_name: "webapp"
    image: "webapp:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      Orleans__Clustering__ProviderType: "Redis"
      Orleans__Clustering__ServiceKey: "redis"
      ConnectionStrings__redis: "redis:6381"
      Orleans__ClusterId: "jjzX!uybz6QTbsbeVLiTB743f"
      Orleans__ServiceId: "PLcLNv3Slz5xCGzwbXykjGuTa"
      Orleans__EnableDistributedTracing: "true"
      Orleans__GrainStorage__games__ProviderType: "Redis"
      Orleans__GrainStorage__games__ServiceKey: "redis"
      Orleans__Endpoints__SiloPort: "8000"
      Orleans__Endpoints__GatewayPort: "8001"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    - target: 8000
      published: 10002
    - target: 8001
      published: 10003
    restart: unless-stopped
volumes:
  redis-data: {}
